workspace:
  base: /go
  path: src/github.com/src-d/lookout

branches: [master]

# ANCHORS

build: &build
  image: golang:1.12-stretch
  commands:
    - make dependencies
    - PKG_OS=linux DOCKER_OS=linux DOCKER_ARCH=amd64 make packages
  debug: true

docker_image: &docker_image
  group: docker
  image: plugins/docker
  registry: docker.io
  repo: srcd/lookout
  secrets: [ docker_username, docker_password ]
  dockerfile: docker/Dockerfile
  debug: true

helm_deploy: &helm_deploy
  image: quay.io/ipedrazas/drone-helm@sha256:43a6e6f907e68925fdb46601981242d68c41eb3e67154d8675627e19fd78f216
  skip_tls_verify: true
  helm_repos: srcd-stable=https://src-d.github.io/charts/stable/
  chart: srcd-stable/lookout
  chart-version: 0.9.0
  release: lookout
  tiller_ns: lookout
  namespace: lookout

# PIPELINE STEPS

pipeline:

  clone:
    image: plugins/git
    debug: true

  # deployment to staging environment when master is pushed

  build_stg:
    <<: *build
    when:
      branch: [master]
      event: [push]

  docker_image_stg:
    <<: *docker_image
    # workaround for bug https://github.com/kubernetes/helm/issues/1707
    tag: 'commit-${DRONE_COMMIT_SHA:0:7}'
    when:
      branch: [master]
      event: [push]

  helm_deploy_stg:
    <<: *helm_deploy
    prefix: STG
    timeout: 900
    secrets: [ STG_API_SERVER, STG_KUBERNETES_TOKEN ]
    values: image.lookout.tag=commit-${DRONE_COMMIT_SHA:0:7}
    values_files: [.helm-staging.yml]
    when:
      branch: [master]
      event: [push]
